### ISSUE TITLE
Game crashes when opening with the plugins

### ISSUE THREAD

**Issue by DemonicWolfZ** [WoodgamerHD/InsidetheBackrooms-cheat#2]
****Hey there, i have been trying to use your plugins, but it seems to crash right away when i try to start up the game
![40f20706c9577f3f1a922313be2d8ba8](https://github.com/WoodgamerHD/InsidetheBackrooms-cheat/assets/146452462/18e352c5-4273-41e2-ab72-858a35f0eae0)

**Comment by WoodgamerHD** [comment]
Cheat for Inside the Backrooms


-how to install-

-install melonloader

-wait for game to fully loaded with melon loader

-then close game

-then put the dll in plugin file and run game
