### ISSUE TITLE
Game performance drops badly when using the menu, also chams cannot be disabled again afterwards

### ISSUE THREAD

**Issue by DemonicWolfZ** [WoodgamerHD/InsidetheBackrooms-cheat#3]
Heyo, so i got the menu working on the game and all, but my fps has dropped really badly after getting the menu 

I used to get like solid 120 fps and no frame drops what so ever, but after getting the menu i only get like 40 to 50 frames

**Comment by WoodgamerHD** [comment]
can you tell me what cheats you are using/what level 

atm i do not get any fps drops on my game?

**Comment by DemonicWolfZ** [comment]
I am using the chems cheat on the sewer level and whenever I try to turn it
off again it just stays on and the game begins to stutter from 140 fps to
45 or so

**Comment by WoodgamerHD** [comment]
do not use the chams for now ill update with it removed soon

**Comment by WoodgamerHD** [comment]
try with the new update i pushed
